services:
  # Представлено для розуміння мапінгу та мережі
  syncthing:
    image: syncthing/syncthing:latest
    container_name: syncthing
    networks:
      - st_net
    volumes:
      - /music:/music # Твоя основна папка з музикою
      - ./syncthing_config:/var/syncthing
    ports:
      - "8384:8384" # Web UI та REST API
      - "22000:22000/tcp"
      - "22000:22000/udp"
    restart: unless-stopped

  # Наш Sidecar-контейнер
  music-tagger:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: music-tagger
    networks:
      - st_net
    depends_on:
      - syncthing
    env_file:
      - .env
    volumes:
      - /music:/music:rw # Спільний доступ до медіатеки (читання/запис)
      - ./tagger_config:/config:rw # Сховище для бази beets (library.db) та його config.yaml
    ports:
      - "8000:8000" # Порт для Prometheus метрик (/metrics)
    restart: unless-stopped

networks:
  st_net:
    driver: bridge
    name: st_net
